"""Self-contained offline HTML; no raw transcript bodies or external assets."""
import json


def render(report):
    payload = {k: report[k] for k in ("client", "path", "tokenizer", "timeline", "context_snapshots", "errors")}
    payload.update(view_kind=report.get("view_kind", "transcript"), coverage_notice=report.get("coverage_notice", "Partial transcript coverage: startup instructions, tool schemas and other unlogged context may be missing. This is not the total model context."))
    payload.update(provenance=report.get('provenance'), lifecycle_events=report.get('lifecycle_events', []))
    data = json.dumps(payload, ensure_ascii=True).replace("<", "\\u003c").replace(">", "\\u003e").replace("&", "\\u0026")
    return TEMPLATE.replace("__AUDIT_DATA__", data)


TEMPLATE = r'''<!doctype html>
<html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Context Audit · Session map</title><style>[hidden]{display:none!important}</style>
<style>
:root{color-scheme:dark;font:15px system-ui;background:#10141c;color:#e7edf7}*{box-sizing:border-box}body{margin:0;padding:32px;max-width:1600px;margin:auto}h1{font-size:32px;margin:8px 0}h2{font-size:18px;margin-top:0}.muted{color:#a4b0c4;line-height:1.6}header{margin-bottom:24px}.eyebrow{font:12px monospace;color:#7dcbbc;letter-spacing:2px}button,select,input{font:inherit}button,select{border:1px solid #394458;background:#1c2433;color:inherit;border-radius:7px;padding:8px;cursor:pointer}button:focus-visible,select:focus-visible{outline:2px solid #fff}.controls{display:flex;gap:16px;align-items:center;flex-wrap:wrap;margin:18px 0}.panel{border:1px solid #2b3547;background:#151c28;border-radius:12px;padding:20px;margin:16px 0}.stats{display:flex;gap:40px;flex-wrap:wrap}.stat strong{font-size:26px;display:block}.legend{display:flex;flex-wrap:wrap;gap:8px}.legend button{font-size:12px}.dot{display:inline-block;width:9px;height:9px;border-radius:50%;margin-right:7px}.off{opacity:.4}#viewport{overflow-x:auto;padding-bottom:12px}#chart{display:block}svg text{fill:#98a6bc;font:11px system-ui}.block{cursor:pointer}.block:focus{outline:none;stroke:white;stroke-width:3}.two{display:grid;grid-template-columns:1fr 1fr;gap:16px}.two .panel{min-width:0}#detail{white-space:pre-wrap;overflow-wrap:anywhere;line-height:1.7}table{width:100%;border-collapse:collapse;font-size:13px}td,th{text-align:left;border-bottom:1px solid #293244;padding:9px;overflow-wrap:anywhere}td:last-child,th:last-child{text-align:right}.list{max-height:400px;overflow:auto}.caption{font-size:12px;color:#a4b0c4}#source{overflow-wrap:anywhere}a{color:#82c8ff}@media(max-width:850px){body{padding:16px}.two{grid-template-columns:1fr}}
</style>
<style>dialog{color:inherit;background:#151c28;border:1px solid #53627d;border-radius:14px;width:min(680px,90vw);max-height:85vh;padding:24px}dialog::backdrop{background:#0009}#inspect-body{white-space:pre-wrap;overflow-wrap:anywhere;line-height:1.8}#inspect-title{overflow-wrap:anywhere}dialog .controls{justify-content:flex-end}</style>
<header><div class="eyebrow">CONTEXT AUDIT / SESSION PROVENANCE</div><h1>Where the context came from</h1><div id="source" class="muted"></div></header>
<div class="panel" id="coverage" role="note"></div>
<div class="stats"><div class="stat"><strong id="total"></strong>recorded text tokens</div><div class="stat"><strong id="blocks"></strong>context blocks</div><div class="stat"><strong id="epochs"></strong>compaction boundaries</div></div>
<div class="panel"><h2>Context timeline</h2><p class="muted">Oldest on the left, newest on the right. Each block is one recorded addition. Click a block to trace its source. Dashed lines mark compaction; earlier blocks are historical and may no longer be retained.</p>
<div class="controls"><label>Spacing <select id="mode"><option value="tokens">Token footprint</option><option value="events">Event order</option></select></label><label>Zoom <input id="zoom" type="range" min="1" max="12" value="1"></label><button id="reset">Show all types</button></div>
<div class="legend" id="legend"></div><div id="viewport"><svg id="chart" role="img" aria-label="Session context timeline"></svg></div>
<p class="caption">Filters dim blocks while preserving positions. Token spacing uses cumulative estimated text tokens; very small blocks have a minimum visible width. Event spacing gives each block equal width.</p></div>
<div class="two"><section class="panel"><h2>Selected injection</h2><div id="detail">Select a block in the timeline.</div><button id="parent" hidden>Trace originating tool call</button></section><section class="panel"><h2>Attribution by source</h2><div class="list"><table><thead><tr><th>Type / source</th><th>Tokens</th></tr></thead><tbody id="sources"></tbody></table></div></section></div>
<section class="panel" id="native"><h2>How context was introduced</h2><p id="native-summary" class="muted"></p><p class="muted">A lifecycle event proves an operation occurred. A call-ID link identifies the operation, but does not prove its output was unchanged. An exact content match confirms matching normalized text. Multiple candidate sources remain ambiguous. Instruction-load events without content cannot be assigned a token cost. Other hooks’ output is not observable through these sibling hooks.</p><div id="native-events" class="list"></div></section>
<section class="panel"><h2>Measurement and coverage</h2><p id="measurement" class="muted"></p><p class="muted">Tool-call JSON is counted separately from tool results. Skill text and file reads replace the generic tool-result category, so they are not counted twice. A linked source is evidence of origin, not proof that all its text remains in the current request. Shell calls may have multiple candidate sources. Hidden tool schemas, unlogged injections, media tokens and reasoning are not reconstructed.</p><p id="snapshot" class="muted"></p><p class="caption">This page contains metadata and hashes, not message bodies or raw tool arguments. Source paths and names remain visible. No external scripts or network requests.</p></section>
<dialog id="inspector" aria-labelledby="inspect-title"><h2 id="inspect-title"></h2><div id="inspect-body"></div><div class="controls"><button id="inspect-origin" hidden>Go to originating call</button><button id="inspect-close">Close</button></div></dialog>
<script type="application/json" id="data">__AUDIT_DATA__</script>
<script>
const report=JSON.parse(document.getElementById('data').textContent),t=report.timeline;
const colors={user:'#76b9ff',assistant:'#c0a2ff','tool-call':'#f6c86c','tool-result':'#70d4c0',skill:'#ed92c8',hook:'#f29d70',file:'#94cc72',instructions:'#a8b9d3',injected:'#dcabfa',summary:'#7ad6e3',compaction:'#ffffff',other:'#8994a4',media:'#d5bda4'};
const $=id=>document.getElementById(id),fmt=n=>Number(n).toLocaleString(),ns='http://www.w3.org/2000/svg',hidden=new Set();let selected;
$('source').textContent=report.client.toUpperCase()+' · '+report.path;
$('coverage').textContent=report.coverage_notice;
if(report.view_kind.startsWith('captured-')){document.querySelector('h1').textContent='Captured context · oldest to newest';const heading=document.querySelector('.panel h2');heading.textContent='Context observation timeline';heading.nextElementSibling.textContent='Older observed content on the left, newer additions on the right. Unchanged tools keep their place as conversation grows. Initial ties put instructions and tools before messages. This shows observed chronology, not the provider’s internal prompt layout.';document.querySelector('.two h2').textContent='Selected context component';colors['tool-definition']='#f6c86c';colors.reasoning='#bb97cb';$('total').parentElement.lastChild.textContent=' measured text/schema tokens';$('epochs').parentElement.lastChild.textContent=' unknown-cost blocks';if(t.unknown_token_blocks){$('mode').value='events';$('mode').options[0].disabled=true;document.querySelector('#viewport + .caption').textContent='Event spacing keeps unknown-cost attachments and legacy unsplit messages visible. Token spacing is unavailable while any block has an unknown cost; unknown does not mean zero.';}}
$('total').textContent=fmt(t.total_recorded_tokens);$('blocks').textContent=fmt(t.blocks.length);$('epochs').textContent=report.view_kind.startsWith('captured-')?t.unknown_token_blocks:t.blocks.filter(b=>b.category==='compaction').length;
if(report.view_kind==='captured-session'){document.querySelector('h1').textContent='Entire observed session context';document.querySelector('.panel h2').nextElementSibling.textContent='All captured context stays visible, oldest on the left and newest on the right. Repeated snapshots do not duplicate unchanged content. Click a block to see which requests contained it. This accumulated history is not a verified current-retention map.';$('total').parentElement.lastChild.textContent=' accumulated observed text/schema tokens';}
$('measurement').textContent=t.measurement+' Encoding: '+report.tokenizer+'. Parse errors: '+report.errors.length+'.';
if(report.view_kind==='captured-pending'){document.querySelector('h1').textContent='Session started · no model request captured yet';document.querySelector('.stats').hidden=true;$('viewport').closest('.panel').hidden=true;document.querySelector('.two').hidden=true;}
const snap=report.context_snapshots.at(-1);$('snapshot').textContent=snap?'Latest independently recorded context snapshot: '+JSON.stringify(snap)+'. This is not the cumulative introduction total shown above.':'No client context snapshot was recorded for this session.';
for(const [cat,count] of Object.entries(t.by_category)){const btn=document.createElement('button'),dot=document.createElement('span');dot.className='dot';dot.style.background=colors[cat];btn.append(dot,document.createTextNode(cat+' · '+fmt(count)+(t.blocks.some(b=>b.category===cat&&b.details.token_cost_unknown)?' + unknown':'')));btn.dataset.cat=cat;btn.onclick=()=>{hidden.has(cat)?hidden.delete(cat):hidden.add(cat);btn.classList.toggle('off',hidden.has(cat));draw()};$('legend').append(btn)}
for(const row of t.by_source){const tr=document.createElement('tr'),a=document.createElement('td'),b=document.createElement('td');a.textContent=row.category+' / '+row.source;b.textContent=row.unknown?'unknown':fmt(row.tokens);tr.append(a,b);$('sources').append(tr)}
function elem(tag,attrs,text){const e=document.createElementNS(ns,tag);for(const [k,v] of Object.entries(attrs))e.setAttribute(k,v);if(text!==undefined)e.textContent=text;return e}
function blockName(b){return b.details.skill||b.details.file_path||b.details.tool||b.source}
function costLabel(b){return b.details.token_cost_unknown?'unknown token cost':fmt(b.tokens)+' tokens'}
function provenanceLines(d){return ['Native attribution: '+(d.provenance_status||'not collected'),...(d.provenance||[]).map(p=>{const s=p.source;return '\n'+p.observation_point+' → '+(s.file_path||s.skill||s.tool||s.label)+' → captured component\nEvidence: '+p.evidence+(p.failed?' (failed operation)':'')+'\nObserved: '+p.timestamp+'\nEvent ID: '+p.event_id+(s.load_reason?'\nLoad reason: '+s.load_reason:'')+(s.parent_file_path?'\nIncluded by: '+s.parent_file_path:'')+(s.trigger_file_path?'\nTriggered by: '+s.trigger_file_path:'')+(s.declared_server?'\nDeclared MCP server: '+s.declared_server+' (not verified plugin ownership)':'')})]}
function identificationLines(d){const i=d.identification||{};return [...(d.observed_in_requests?['Observed in requests: '+d.observed_in_requests.join(', ')]:[]),...(d.retention?['Retention evidence: '+d.retention]:[]),...(d.first_seen_request!==undefined?['First observed in request: '+d.first_seen_request]:[]),...(d.measurement?['Measurement: '+d.measurement]:[]),...(d.media?['Attachment metadata: '+JSON.stringify(d.media)]:[]),...(d.json_pointer?['Request location: '+d.json_pointer]:[]),...(i.sections?.length?['Identified contents:\n  '+i.sections.join('\n  ')]:[]),...(i.declared_skills?.length?['Declared skills (not proof of use):\n  '+i.declared_skills.map(s=>s.name+' — '+s.path).join('\n  ')]:[]),...(i.tool_namespaces?.length?['Tool namespaces: '+i.tool_namespaces.join(', ')]:[]),...(i.declared_tools?.length?['Declared tools: '+i.declared_tools.join(', ')]:[]),...(i.identification_evidence?['Identification evidence: '+i.identification_evidence]:[]),...(i.origin_status?['Origin: '+i.origin_status]:[]),...(d.source_ids?.length?['Matching registered sources: '+d.source_ids.join(', ')]:[])]}
function select(b){selected=b.id;const d=b.details;const lines=[b.category.toUpperCase()+' · '+(d.token_cost_unknown?'unknown token cost':fmt(b.tokens)+' estimated tokens'),...(d.tool?['Tool: '+d.tool]:[]),...(d.skill?['Skill: '+d.skill]:[]),...(d.file_path?['File: '+d.file_path]:[]),...['offset','limit','start_line','end_line'].filter(k=>d[k]!==undefined).map(k=>k+': '+d[k]),...identificationLines(d),'Source: '+b.source,'Evidence: '+b.evidence,...(d.json_pointer?[]:['Transcript line: '+b.line]),'Time: '+(b.timestamp||'not recorded'),'Compaction epoch: '+b.epoch,'Cumulative interval: '+fmt(b.start_token)+'–'+fmt(b.end_token),...(d.call_id?['Call ID: '+d.call_id]:[]),...(d.failed?['Status: failed']:[]),...(d.candidate_sources?.length?['Possible sources (unverified): '+d.candidate_sources.join(', ')]:[]),(d.fingerprint_type||'SHA-256')+': '+b.sha256];$('detail').textContent=lines.join('\n');$('inspect-title').textContent=blockName(b);$('inspect-body').textContent=lines.join('\n');$('parent').hidden=!b.parent;$('inspect-origin').hidden=!b.parent;const origin=()=>{const p=t.blocks.find(x=>x.id===b.parent);if(p){select(p);document.getElementById(p.id)?.scrollIntoView({block:'nearest',inline:'center'})}};$('parent').onclick=origin;$('inspect-origin').onclick=origin;draw();if(!$('inspector').open)$('inspector').showModal()}
$('inspect-close').onclick=()=>$('inspector').close();$('inspector').addEventListener('click',e=>{if(e.target===$('inspector')){const r=e.target.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)e.target.close()}});
const identifyContents=identificationLines;identificationLines=d=>[...(d.first_observation_kind?['First observation: '+d.first_observation_kind]:[]),...provenanceLines(d),...identifyContents(d)];
const p=report.provenance;
$('native-summary').textContent=p?`${p.native_events} native events · ${p.linked_blocks}/${p.total_blocks} blocks linked · ${p.ambiguous_blocks} blocks with competing sources · ${p.unmatched_events} events without a matching block. Links are evidence, not a completeness score.`:'Native lifecycle collection was not present in this recording. Existing request metadata cannot reconstruct missing hook events.';
for(const e of report.lifecycle_events){const row=document.createElement('details'),title=document.createElement('summary'),body=document.createElement('div');title.textContent=e.observation_point+' · '+(e.source.file_path||e.source.skill||e.source.tool||e.source.label)+' · '+(e.linked?'linked':'no content link');body.style.whiteSpace='pre-wrap';body.textContent='Observed: '+e.timestamp+'\n'+Object.entries(e.source).map(([k,v])=>k+': '+v).join('\n');row.append(title,body);for(const id of e.blocks){const button=document.createElement('button');button.textContent='Inspect '+id;button.onclick=()=>select(t.blocks.find(b=>b.id===id));row.append(button)}$('native-events').append(row)}
function draw(){const svg=$('chart');svg.replaceChildren();const width=Math.max(800,$('viewport').clientWidth)*Number($('zoom').value),pad=25,usable=width-pad*2;svg.setAttribute('width',width);svg.setAttribute('height',240);const n=Math.max(t.blocks.length,1),total=Math.max(t.total_recorded_tokens,1),byTokens=$('mode').value==='tokens';const x=(b,i)=>pad+usable*(byTokens?b.start_token/total:i/n);svg.append(elem('line',{x1:pad,y1:160,x2:width-pad,y2:160,stroke:'#3b475c'}));
for(let i=0;i<=4;i++){const xx=pad+usable*i/4;svg.append(elem('text',{x:xx,y:188,'text-anchor':i===4?'end':'start'},byTokens?fmt(Math.round(total*i/4))+' tokens':Math.round(n*i/4)+' events'))}
t.blocks.forEach((b,i)=>{const xx=x(b,i),w=Math.max(2,usable*(byTokens?b.tokens/total:1/n)-1);if(b.category==='compaction'){svg.append(elem('line',{x1:xx,y1:22,x2:xx,y2:164,stroke:'#fff','stroke-dasharray':'4 4'}));svg.append(elem('text',{x:xx+4,y:18},'compact '+b.epoch));return}const height=35+Math.min(85,Math.log2(b.tokens+1)*6),rect=elem('rect',{id:b.id,x:xx,y:160-height,width:w,height,rx:2,fill:colors[b.category]||colors.other,opacity:hidden.has(b.category)?'.08':'1',class:'block',tabindex:0,role:'button','aria-label':b.category+', '+b.source+', '+costLabel(b),stroke:selected===b.id?'white':'none','stroke-width':2});rect.append(elem('title',{},b.category+' / '+b.source+' / '+costLabel(b)));rect.onclick=()=>select(b);rect.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();select(b)}};svg.append(rect)});
svg.append(elem('text',{x:pad,y:222},'FIRST RECORDED CONTEXT →'));svg.append(elem('text',{x:width-pad,y:222,'text-anchor':'end'},'MOST RECENT →'))}
$('zoom').oninput=draw;$('mode').onchange=draw;$('reset').onclick=()=>{hidden.clear();document.querySelectorAll('.legend button').forEach(b=>b.classList.remove('off'));draw()};window.addEventListener('resize',draw);draw();
</script></html>'''
